# platform :ios, '11.0'

# require File.expand_path('../flutter_export_environment', __FILE__)
# require File.expand_path('../.flutter-plugins-dependencies', __FILE__)

# target 'Runner' do
#   use_frameworks!
#   use_modular_headers!

#   flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

#   target 'RunnerTests' do
#     inherit! :search_paths
#   end
# end
